### ISSUE TITLE
After updating to Pixi v6.5.8 Robotlegs mediator's aren't getting initialised

### ISSUE THREAD

**Issue by danrostron** [RobotlegsJS/RobotlegsJS-Framework#42]
Hi @tiagoschenkel , I've finally updated our code base to use Pixi v6.5.8 (which took some time due to issues with Pixi layers), and Robotlegs 3, however after running our code (no compile errors) I've discovered that after adding child views, the associated mediators are never getting initialised. Any idea why?

We're using Pixi legacy to support canvas fallback. Here's the package versions we're using:

```
        "@robotlegsjs/core": "^3.1.0",
        "@robotlegsjs/macrobot": "^3.1.0",
        "@robotlegsjs/pixi": "^4.0.0",
        "@robotlegsjs/signalcommandmap": "^3.1.0",

        "pixi.js-legacy": "^6.5.8",
        "pixi-spine": "^3.1.0",
        "@pixi/graphics-extras": "^7.0.5",
        "@pixi/layers": "^1.0.11",
```
I know you mentioned about Pixi had changed to use EventEmitter3, but we're not getting any compile errors - or even runtime errors. It just silently fails to intialise any mediators. Using the normal method of registering mediators as follows:

```
@inject(IMediatorMap)
protected _mediatorMap: IMediatorMap;

// register view/mediator
this._mediatorMap.map(MainGameView).toMediator(MainGameMediator);

// add view
 const mainGameView: MainGameView= new MainGameView();
 gameContainer.addChild(mainGameView);
```

Thanks in advance
Dan

**Comment by danrostron** [comment]
I'm not sure whether the problem is due to the change I had to make to tsconfig.json. In Robotlegs docs you state we should use the following:

```
{
    "compilerOptions": {
        "target": "es5",
        "lib": ["es6", "dom"],
        "types": ["reflect-metadata"],
        "module": "commonjs",
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    }
}
```
However, I recently had to change the module option to be `ES2015` instead of `commonjs`. The reason was because, otherwise I will get runtime errors from Pixi layers:

Uncaught TypeError: renderer.incDisplayOrder is not a function

Not sure if this change of module system would affect the mediators in Robotlegs?

**Comment by danrostron** [comment]
I've confirmed that changing the example game (ie. Battleship) to ES6 module format that it's also affected by the same problem, the mediator's are never initialised.

Any ideas about how to resolve this @tiagoschenkel @RonaldoSetzer ?

**Comment by tiagoschenkel** [comment]
Hi @danrostron, there are two different things to take into consideration:

- Usage of `"pixi.js-legacy"` instead of `"pixi.js"`:

Our plugin is made for the `"pixi.js"` package, not for the `"pixi.js-legacy"` package.

The integration with RobotlegsJS depends on a patch that we are applying to the `Container` class, since we need to trigger the `"added"` (to the stage) and `"removed"` (from the stage) events, so the mediator layer knows that some visual element was added and removed, and can manage the respective mediators.

You can see here that we need to import some classes from `"pixi.js"` library, then we add the event triggers:
https://github.com/RobotlegsJS/RobotlegsJS-Framework/blob/master/packages/pixi/src/robotlegs/bender/extensions/contextView/pixiPatch/pixi-patch.ts#L14

This means that, indeed, no mediator will be created when child elements are added to the stage, and this is because you are using `"pixi.js-legacy"` classes, so the child elements will not trigger the `"added"` nor  `"removed"` events.

To solve this issue, we need to create another plugin for the `"pixi.js-legacy"` package.

- Usage of `"es2015"` instead of `"commonjs"`

Indeed, we are using the `"commonjs"` module system, and this is because internally the RobotlegsJS core depends on the [InversifyJS](https://github.com/inversify/InversifyJS) library, used for inversion of control.

I don't know if we can use `"es2015"` and still import the `InversifyJS` classes from `"commonjs"`.

**Comment by danrostron** [comment]
Thanks for the response @tiagoschenkel. 

It seems that pixi.js-legacy uses pixi.js under the hood, so that doesn't appear to be the issue.

After debugging I've found the issue is the way you export the module in pixi-patch.ts. The overridden Container class comes from `node_modules/@pixi/display/dist/cjs/display.js` however the Container class that Pixi uses comes from `node_modules/@pixi/display/dist/esm/display.mjs` and so the patchedAddChild function never gets called.

I therefore changed the pixi-patch.ts to use import/export format instead of require syntax and it works - however I'm currently just modifying files in node_modules. I can see in your source file pixi-patch.ts you're also using import/export, so it must be to do with the module format (commonJS) you are using to build/publish the pixi extension.

I think I probably need to change your module format to be ES2015, publish to our own Gitlab repository, and then install from this repo instead of your one. Not quite sure how to do that from this mono repo thing though....

**Comment by danrostron** [comment]
Figured it out in the end, thanks @tiagoschenkel. I did indeed need to build the Robotlegs Pixi extension using module format ES2015.
